/* Generated By:JavaCC: Do not edit this line. parserSQLConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parserSQLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int validar = 1;
  /** RegularExpression Id. */
  int login = 2;
  /** RegularExpression Id. */
  int comando = 3;
  /** RegularExpression Id. */
  int password = 4;
  /** RegularExpression Id. */
  int paquete = 5;
  /** RegularExpression Id. */
  int instruccion = 6;
  /** RegularExpression Id. */
  int text = 7;
  /** RegularExpression Id. */
  int integer = 8;
  /** RegularExpression Id. */
  int doble = 9;
  /** RegularExpression Id. */
  int bool = 10;
  /** RegularExpression Id. */
  int date = 11;
  /** RegularExpression Id. */
  int dateTime = 12;
  /** RegularExpression Id. */
  int crear = 13;
  /** RegularExpression Id. */
  int tabla = 14;
  /** RegularExpression Id. */
  int objeto = 15;
  /** RegularExpression Id. */
  int procedimiento = 16;
  /** RegularExpression Id. */
  int funcion = 17;
  /** RegularExpression Id. */
  int retorno = 18;
  /** RegularExpression Id. */
  int usuario = 19;
  /** RegularExpression Id. */
  int usar = 20;
  /** RegularExpression Id. */
  int alterar = 21;
  /** RegularExpression Id. */
  int eliminar = 22;
  /** RegularExpression Id. */
  int insertar = 23;
  /** RegularExpression Id. */
  int actualizar = 24;
  /** RegularExpression Id. */
  int borrar = 25;
  /** RegularExpression Id. */
  int seleccionar = 26;
  /** RegularExpression Id. */
  int otorgar = 27;
  /** RegularExpression Id. */
  int denegar = 28;
  /** RegularExpression Id. */
  int declarar = 29;
  /** RegularExpression Id. */
  int si = 30;
  /** RegularExpression Id. */
  int sino = 31;
  /** RegularExpression Id. */
  int selecciona = 32;
  /** RegularExpression Id. */
  int caso = 33;
  /** RegularExpression Id. */
  int defecto = 34;
  /** RegularExpression Id. */
  int para = 35;
  /** RegularExpression Id. */
  int mientras = 36;
  /** RegularExpression Id. */
  int detener = 37;
  /** RegularExpression Id. */
  int imprimir = 38;
  /** RegularExpression Id. */
  int fecha = 39;
  /** RegularExpression Id. */
  int contar = 40;
  /** RegularExpression Id. */
  int backup = 41;
  /** RegularExpression Id. */
  int usqldump = 42;
  /** RegularExpression Id. */
  int completo = 43;
  /** RegularExpression Id. */
  int restaurar = 44;
  /** RegularExpression Id. */
  int parentesisA = 45;
  /** RegularExpression Id. */
  int parentesisC = 46;
  /** RegularExpression Id. */
  int llaveA = 47;
  /** RegularExpression Id. */
  int llaveC = 48;
  /** RegularExpression Id. */
  int corcheteA = 49;
  /** RegularExpression Id. */
  int corcheteC = 50;
  /** RegularExpression Id. */
  int puntoComa = 51;
  /** RegularExpression Id. */
  int dosPuntos = 52;
  /** RegularExpression Id. */
  int mas = 53;
  /** RegularExpression Id. */
  int menos = 54;
  /** RegularExpression Id. */
  int por = 55;
  /** RegularExpression Id. */
  int div = 56;
  /** RegularExpression Id. */
  int potencia = 57;
  /** RegularExpression Id. */
  int igualIgual = 58;
  /** RegularExpression Id. */
  int diferente = 59;
  /** RegularExpression Id. */
  int mayor = 60;
  /** RegularExpression Id. */
  int menor = 61;
  /** RegularExpression Id. */
  int mayorIgual = 62;
  /** RegularExpression Id. */
  int menorIgual = 63;
  /** RegularExpression Id. */
  int or = 64;
  /** RegularExpression Id. */
  int and = 65;
  /** RegularExpression Id. */
  int not = 66;
  /** RegularExpression Id. */
  int numero = 67;
  /** RegularExpression Id. */
  int id = 68;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"validar\"",
    "\"login\"",
    "\"comando\"",
    "\"password\"",
    "\"paquete\"",
    "\"instruccion\"",
    "\"text\"",
    "\"integer\"",
    "\"double\"",
    "\"bool\"",
    "\"date\"",
    "\"dateTime\"",
    "\"crear\"",
    "\"tabla\"",
    "\"objeto\"",
    "\"procedimiento\"",
    "\"funcion\"",
    "\"retorno\"",
    "\"usuario\"",
    "\"usar\"",
    "\"alterar\"",
    "\"eliminar\"",
    "\"insertar\"",
    "\"actualizar\"",
    "\"borrar\"",
    "\"seleccionar\"",
    "\"otorgar\"",
    "\"denegar\"",
    "\"declarar\"",
    "\"si\"",
    "\"sino\"",
    "\"selecciona\"",
    "\"caso\"",
    "\"defecto\"",
    "\"para\"",
    "\"mientras\"",
    "\"detener\"",
    "\"imprimir\"",
    "\"fecha\"",
    "\"contar\"",
    "\"backup\"",
    "\"usqldump\"",
    "\"completo\"",
    "\"restaurar\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\":\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "<numero>",
    "<id>",
    "\" \"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
