/* Generated By:JavaCC: Do not edit this line. parserSQLConstants.java */
package AnalizadorSQL;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parserSQLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int validar = 1;
  /** RegularExpression Id. */
  int login = 2;
  /** RegularExpression Id. */
  int comando = 3;
  /** RegularExpression Id. */
  int password = 4;
  /** RegularExpression Id. */
  int paquete = 5;
  /** RegularExpression Id. */
  int instruccion = 6;
  /** RegularExpression Id. */
  int text = 7;
  /** RegularExpression Id. */
  int integer = 8;
  /** RegularExpression Id. */
  int doble = 9;
  /** RegularExpression Id. */
  int bool = 10;
  /** RegularExpression Id. */
  int date = 11;
  /** RegularExpression Id. */
  int dateTime = 12;
  /** RegularExpression Id. */
  int crear = 13;
  /** RegularExpression Id. */
  int base_datos = 14;
  /** RegularExpression Id. */
  int tabla = 15;
  /** RegularExpression Id. */
  int objeto = 16;
  /** RegularExpression Id. */
  int procedimiento = 17;
  /** RegularExpression Id. */
  int funcion = 18;
  /** RegularExpression Id. */
  int retorno = 19;
  /** RegularExpression Id. */
  int usuario = 20;
  /** RegularExpression Id. */
  int usar = 21;
  /** RegularExpression Id. */
  int alterar = 22;
  /** RegularExpression Id. */
  int eliminar = 23;
  /** RegularExpression Id. */
  int insertar = 24;
  /** RegularExpression Id. */
  int actualizar = 25;
  /** RegularExpression Id. */
  int borrar = 26;
  /** RegularExpression Id. */
  int seleccionar = 27;
  /** RegularExpression Id. */
  int otorgar = 28;
  /** RegularExpression Id. */
  int denegar = 29;
  /** RegularExpression Id. */
  int declarar = 30;
  /** RegularExpression Id. */
  int si = 31;
  /** RegularExpression Id. */
  int sino = 32;
  /** RegularExpression Id. */
  int selecciona = 33;
  /** RegularExpression Id. */
  int caso = 34;
  /** RegularExpression Id. */
  int defecto = 35;
  /** RegularExpression Id. */
  int para = 36;
  /** RegularExpression Id. */
  int mientras = 37;
  /** RegularExpression Id. */
  int detener = 38;
  /** RegularExpression Id. */
  int imprimir = 39;
  /** RegularExpression Id. */
  int fecha = 40;
  /** RegularExpression Id. */
  int fechaHora = 41;
  /** RegularExpression Id. */
  int contar = 42;
  /** RegularExpression Id. */
  int backup = 43;
  /** RegularExpression Id. */
  int usqldump = 44;
  /** RegularExpression Id. */
  int completo = 45;
  /** RegularExpression Id. */
  int nulo = 46;
  /** RegularExpression Id. */
  int no = 47;
  /** RegularExpression Id. */
  int autoincrementable = 48;
  /** RegularExpression Id. */
  int llave_primaria = 49;
  /** RegularExpression Id. */
  int llave_foranea = 50;
  /** RegularExpression Id. */
  int agregar = 51;
  /** RegularExpression Id. */
  int quitar = 52;
  /** RegularExpression Id. */
  int cambiar = 53;
  /** RegularExpression Id. */
  int user = 54;
  /** RegularExpression Id. */
  int verdadero = 55;
  /** RegularExpression Id. */
  int falso = 56;
  /** RegularExpression Id. */
  int en = 57;
  /** RegularExpression Id. */
  int valores = 58;
  /** RegularExpression Id. */
  int donde = 59;
  /** RegularExpression Id. */
  int ordenar = 60;
  /** RegularExpression Id. */
  int permisos = 61;
  /** RegularExpression Id. */
  int asc = 62;
  /** RegularExpression Id. */
  int desc = 63;
  /** RegularExpression Id. */
  int ppor = 64;
  /** RegularExpression Id. */
  int de = 65;
  /** RegularExpression Id. */
  int restaurar = 66;
  /** RegularExpression Id. */
  int parentesisA = 67;
  /** RegularExpression Id. */
  int parentesisC = 68;
  /** RegularExpression Id. */
  int llaveA = 69;
  /** RegularExpression Id. */
  int llaveC = 70;
  /** RegularExpression Id. */
  int corcheteA = 71;
  /** RegularExpression Id. */
  int corcheteC = 72;
  /** RegularExpression Id. */
  int puntoComa = 73;
  /** RegularExpression Id. */
  int dosPuntos = 74;
  /** RegularExpression Id. */
  int mas = 75;
  /** RegularExpression Id. */
  int menos = 76;
  /** RegularExpression Id. */
  int por = 77;
  /** RegularExpression Id. */
  int div = 78;
  /** RegularExpression Id. */
  int potencia = 79;
  /** RegularExpression Id. */
  int igualIgual = 80;
  /** RegularExpression Id. */
  int diferente = 81;
  /** RegularExpression Id. */
  int mayormayor = 82;
  /** RegularExpression Id. */
  int menormenor = 83;
  /** RegularExpression Id. */
  int mayor = 84;
  /** RegularExpression Id. */
  int menor = 85;
  /** RegularExpression Id. */
  int mayorIgual = 86;
  /** RegularExpression Id. */
  int menorIgual = 87;
  /** RegularExpression Id. */
  int or = 88;
  /** RegularExpression Id. */
  int and = 89;
  /** RegularExpression Id. */
  int not = 90;
  /** RegularExpression Id. */
  int coma = 91;
  /** RegularExpression Id. */
  int igual = 92;
  /** RegularExpression Id. */
  int punto = 93;
  /** RegularExpression Id. */
  int entero = 94;
  /** RegularExpression Id. */
  int decimal = 95;
  /** RegularExpression Id. */
  int id = 96;
  /** RegularExpression Id. */
  int idVar = 97;
  /** RegularExpression Id. */
  int simbolo = 98;
  /** RegularExpression Id. */
  int cadena = 99;
  /** RegularExpression Id. */
  int ffecha = 100;
  /** RegularExpression Id. */
  int comentarioSimple = 108;
  /** RegularExpression Id. */
  int comentarioMulti = 109;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"validar\"",
    "\"login\"",
    "\"comando\"",
    "\"password\"",
    "\"paquete\"",
    "\"instruccion\"",
    "\"text\"",
    "\"integer\"",
    "\"double\"",
    "\"bool\"",
    "\"date\"",
    "\"dateTime\"",
    "\"crear\"",
    "\"base_datos\"",
    "\"tabla\"",
    "\"objeto\"",
    "\"procedimiento\"",
    "\"funcion\"",
    "\"retorno\"",
    "\"usuario\"",
    "\"usar\"",
    "\"alterar\"",
    "\"eliminar\"",
    "\"insertar\"",
    "\"actualizar\"",
    "\"borrar\"",
    "\"seleccionar\"",
    "\"otorgar\"",
    "\"denegar\"",
    "\"declarar\"",
    "\"si\"",
    "\"sino\"",
    "\"selecciona\"",
    "\"caso\"",
    "\"defecto\"",
    "\"para\"",
    "\"mientras\"",
    "\"detener\"",
    "\"imprimir\"",
    "\"fecha\"",
    "\"fecha_hora\"",
    "\"contar\"",
    "\"backup\"",
    "\"usqldump\"",
    "\"completo\"",
    "\"nulo\"",
    "\"no\"",
    "\"autoincrementable\"",
    "\"llave_primaria\"",
    "\"llave_foranea\"",
    "\"agregar\"",
    "\"quitar\"",
    "\"cambiar\"",
    "\"user\"",
    "\"verdadero\"",
    "\"falso\"",
    "\"en\"",
    "\"valores\"",
    "\"donde\"",
    "\"ordenar\"",
    "\"permisos\"",
    "\"asc\"",
    "\"desc\"",
    "\"por\"",
    "\"de\"",
    "\"restaurar\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\":\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"==\"",
    "\"!=\"",
    "\">>\"",
    "\"<<\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "\",\"",
    "\"=\"",
    "\".\"",
    "<entero>",
    "<decimal>",
    "<id>",
    "<idVar>",
    "<simbolo>",
    "<cadena>",
    "<ffecha>",
    "\" \"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\u00a0\"",
    "<comentarioSimple>",
    "<comentarioMulti>",
  };

}
