/* Generated By:JavaCC: Do not edit this line. parserXMLConstants.java */
package AnalizadorXML;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parserXMLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int db = 1;
  /** RegularExpression Id. */
  int nombreA = 2;
  /** RegularExpression Id. */
  int nombreC = 3;
  /** RegularExpression Id. */
  int path = 4;
  /** RegularExpression Id. */
  int procedure = 5;
  /** RegularExpression Id. */
  int rows = 6;
  /** RegularExpression Id. */
  int object = 7;
  /** RegularExpression Id. */
  int tipoInt = 8;
  /** RegularExpression Id. */
  int tipoText = 9;
  /** RegularExpression Id. */
  int tipoBool = 10;
  /** RegularExpression Id. */
  int proc = 11;
  /** RegularExpression Id. */
  int params = 12;
  /** RegularExpression Id. */
  int crear = 13;
  /** RegularExpression Id. */
  int obj = 14;
  /** RegularExpression Id. */
  int atr = 15;
  /** RegularExpression Id. */
  int tabla = 16;
  /** RegularExpression Id. */
  int maestro = 17;
  /** RegularExpression Id. */
  int basedatos = 18;
  /** RegularExpression Id. */
  int parentesisA = 19;
  /** RegularExpression Id. */
  int parentesisC = 20;
  /** RegularExpression Id. */
  int llaveA = 21;
  /** RegularExpression Id. */
  int llaveC = 22;
  /** RegularExpression Id. */
  int corcheteA = 23;
  /** RegularExpression Id. */
  int corcheteC = 24;
  /** RegularExpression Id. */
  int puntoComa = 25;
  /** RegularExpression Id. */
  int dosPuntos = 26;
  /** RegularExpression Id. */
  int etqC = 27;
  /** RegularExpression Id. */
  int etqA = 28;
  /** RegularExpression Id. */
  int entero = 29;
  /** RegularExpression Id. */
  int decimal = 30;
  /** RegularExpression Id. */
  int id = 31;
  /** RegularExpression Id. */
  int simbolo = 32;
  /** RegularExpression Id. */
  int cadena = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"db\"",
    "\"<nombre>\"",
    "\"</nombre>\"",
    "\"path\"",
    "\"procedure\"",
    "\"rows\"",
    "\"object\"",
    "\"int\"",
    "\"text\"",
    "\"bool\"",
    "\"proc\"",
    "\"params\"",
    "\"crear\"",
    "\"obj\"",
    "\"atr\"",
    "\"tabla\"",
    "\"maestro\"",
    "\"baseDatos\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\":\"",
    "\">\"",
    "\"<\"",
    "<entero>",
    "<decimal>",
    "<id>",
    "<simbolo>",
    "<cadena>",
    "\" \"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\u00a0\"",
  };

}
