/* Generated By:JavaCC: Do not edit this line. parserXMLConstants.java */
package AnalizadorXML;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parserXMLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int etqA = 1;
  /** RegularExpression Id. */
  int etqB = 2;
  /** RegularExpression Id. */
  int etqC = 3;
  /** RegularExpression Id. */
  int entero = 4;
  /** RegularExpression Id. */
  int decimal = 5;
  /** RegularExpression Id. */
  int id = 6;
  /** RegularExpression Id. */
  int cadena = 7;
  /** RegularExpression Id. */
  int cad = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"<\"",
    "\"</\"",
    "\">\"",
    "<entero>",
    "<decimal>",
    "<id>",
    "<cadena>",
    "<cad>",
    "\" \"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\u00a0\"",
  };

}
